include_controls 'ssh-baseline' do
    skip_control 'ssh-02'
    skip_control 'ssh-03'
    skip_control 'ssh-04'
    skip_control 'ssh-05'
    skip_control 'ssh-06'
    skip_control 'ssh-07'
    skip_control 'ssh-08'
    skip_control 'ssh-09'
    skip_control 'ssh-10'
    skip_control 'ssh-11'
    skip_control 'ssh-12'
    skip_control 'ssh-13'
    skip_control 'ssh-14'
    skip_control 'ssh-15'
    skip_control 'ssh-16'
    skip_control 'ssh-17'
    skip_control 'ssh-19'
    skip_control 'ssh-20'
    skip_control 'sshd-14'
    skip_control 'sshd-20'
    skip_control 'sshd-21'
    skip_control 'sshd-48'
end
